---
# tasks file for dev_F5_pool_mark_up_process
- name: Passed input values F5 mark up
  debug:
    msg: 
      - "{{ partition }}"
      - "{{ pool_name }}"

- name: Mark up f5 pool members
  include_role:
    name: f5_pool_member_manager_role
  vars:
    test_mode: false
    run_tests: "happy_path_mark_up"
    operation: "mark-down"