---
- name: Mark dev F5 pools up
  connection: local
  gather_facts: false
  hosts: dev_f5

  tasks:
    - name: Get credentials
      set_fact:
        ansible_user: "{{ lookup('env', 'ANSIBLE_NET_USERNAME')}}"
        ansible_password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD' )}}"
      failed_when:
       - not ansible_user
       - not ansible_password
      no_log: false
      tags: audit

    - name: Pull out resource variables from service definition
      set_fact:
        service_resources: "{{ next_definition }}"
      loop: "{{ dev_resource_definition }}"
      loop_control:
        loop_var: next_definition
      when: next_definition.name == "dev_resource_group"
      tags: audit
    
    - name: Fail if no data found
      fail:
        msg: "Failure due to no data found"
      when: service_resources is undefined
      tags: audit

    - name: Mark up f5 pools
      block:
        - name: check state of F5 and set device details.
          include_role:
            name: f5_single_device_manager_role
          vars:
            test_mode: true
            operation: "happy_path_active"

        - name: Loop over the pools and mark up
          include_role:
            name: dev_F5_pool_mark_up_process
          vars:
            partition: "{{ service_resources.partition }}"
            pool_name: "{{ next_pool }}"
          loop: "{{ service_resources.pool_names }}"
          loop_control:
           loop_var: next_pool




