---
- name: Mark banking app DU F5 pools up
  connection: local
  gather_facts: false
  hosts: uat_f5

  tasks:
    - name: Get credentials
      set_fact:
        ansible_user: "{{ lookup('env', 'ANSIBLE_NET_USERNAME')}}"
        ansible_password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD' )}}"
      failed_when:
       - not ansible_user
       - not ansible_password
      no_log: false
      tags: audit

    - name: login to device 
      block:
        - name: Test HA 
          include_role:
            name: f5_ha_device_manager_role