---
- name: test
  hosts: dev_banking_app_f5
  connection: local
  gather_facts: false

  tasks:
  - name: Get credentials
    set_fact:
        ansible_user: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
        ansible_password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD')}}"
    failed_when:
      - not ansible_user
      - not ansible_password
    no_log: false
    tags: audit

  - name: Get pool states from the active F5
    bigip_device_info:
      gather_subset:
       - ltm-pools
      provider:
        server: "{{ ansible_host }}"
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        no_f5_teem: true
        server_port: 443
        validate_certs: False
    register: pool_data
    delegate_to: localhost
    tags: audit

  - name: Parse pool data to pool of interests
    set_fact:
      parsed_pool_data: "{{ item }}"
    loop: "{{ pool_data.ltm_pools }}"
    when: pool_name == item.name
    tags: audit

  #- name: Set pool member filter.
   # set_fact:
   # f5_pool_member_filter:  "{{ next_filter.filter_list }}"
   # loop: "{{ f5_pool_filters }}"
   # loop_control:
   # loop_var: next_filter
   # when: f5_pool_filters is defined and next_filter.pool_name == pool_name
