---

- name: Set fact for operation 
  set_fact:
    service_operation: "{{ item['status'] }}"
  loop: "{{ gtm_pool_state_list }}"
  when: item.operation == operation

- name: Change of GSLB pool member using REST
  uri: 
    url: https://{{ ansible_host }}//mgmt/tm/gtm/pool/a/{{ item['poolName']['description'] | replace('/','~') }}/members/{{ item['serverName']['description'] | replace('/','~') }}:{{ item['vsName']['description'] | replace('/','~')  }} 
    method: PATCH
    validate_certs: false
    headers:
       X-F5-Auth-Token: "{{ bigip_auth_token }}" 
    body: "{{ service_operation }}"
    body_format: json
  delegate_to: localhosts
  register: rest
  when: "pool_member_prefix in item['vsName']['description']"
  loop: "{{ parsed_gtm_pool_stats }}"