---
# tasks file for f5_gslb_role
- name: Retrieve availability status of GTM pool members
  uri: 
    url: https://{{ ansible_host }}/mgmt/tm/gtm/pool/a/~{{ partition }}~{{ gslb_pool_name }}/members/stats
    method: GET
    validate_certs: false
    headers:
       X-F5-Auth-Token: "{{ bigip_auth_token }}" 
    body:
  delegate_to: localhosts
  register: output_stats

- name: Gather gtm pools of interest statistics
  set_fact:
    parsed_gtm_pool_stats: "{{ parsed_gtm_pool_stats + [item['value']['nestedStats']['entries']] }}"
  loop: "{{ output_stats['json']['entries'] | dict2items }}"

- name: change pool state
  include_tasks: change_gslb_state.yml
