---
- name: Send new state to pool using REST
  uri: 
   url: https://{{ ansible_host }}/mgmt/tm/ltm/pool/~{{ partition }}~{{ pool_name }}/members/~{{ partition }}~{{ next_pool_member.name }}
   method: PUT
   body_format: json
   validate_certs: false
   headers:
     X-F5-Auth-Token: "{{ bigip_auth_token }}" 
   body:
     state: "{{ new_pool_state.state }}"
     session: "{{ new_pool_state.session }}"
  loop: "{{ parsed_pool_data.members }}"
  loop_control:
    pause: 2
    loop_var: next_pool_member
  delegate_to: localhost
